excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://f-105w.github.io
title: F-105W
tagline: A little time for security
description: Security, privacy and technology.
paginate: 5
